version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./daos-backend
    ports:
      - 3000:3000
    environment:
      PORT: 1337
      MONGODB_URI: mongodb://mongo_db:27017/daos
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    container_name: database
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./daos-frontend
    ports:
      - 5500:5500
volumes:
  mongo_db: {}